### ISSUE TITLE
Disable Plugin is not working

### ISSUE THREAD

**Issue by MohankumarD** [ralemy/pf4j-spring-tutorial#1]
I have created a disabled.txt file in the plugins folder and added plugin-id to disable. Its shows me in disable list but is resolved and I am able to access plugin feature.

`**pf4j-spring_0.5.0.jar**`

c.q.s.SpringcontainerApplication : Starting SpringcontainerApplication on Qrz-Mohan with PID 10596
c.q.s.SpringcontainerApplication : No active profile set, falling back to default profiles: default
org.pf4j.DefaultPluginStatusProvider : Enabled plugins: []
org.pf4j.DefaultPluginStatusProvider : Disabled plugins: [spring-plugin]
org.pf4j.DefaultPluginManager : PF4J version 2.3.0 in 'deployment' mode
org.pf4j.CompoundPluginDescriptorFinder : C:\plugins\springplugin-1.0.0.jar
org.pf4j.AbstractPluginManager : Plugin 'plugins\springplugin-1.0.0.jar' is disabled
org.pf4j.AbstractPluginManager : Plugin 'spring-plugin@1.0.0' resolved
org.pf4j.AbstractPluginManager : Start plugin 'spring-plugin@1.0.0'
Spring Sample plugin.start()
o.s.b.web.embedded.netty.NettyWebServer : Netty started on port(s): 9090
c.q.s.SpringcontainerApplication : Started SpringcontainerApplication in 4.557 seconds (JVM running for 6.795)
Number of plugins found: 1

**Comment by ralemy** [comment]
Thank you for reviewing the tutorial, Mohankumar. 

Yes, the plugin is found, but it should not allow you to access its endpoints. Do you have any restful endpoints on your plugin? and can you verify that you can access them?
